// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace tradebot_sqlite.Migrations
{
    [DbContext(typeof(TradeHistoryContext))]
    [Migration("20191003122355_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("DbPlacedOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AskFillInfo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AskOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AskPrice")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<string>("AskQuote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AskTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BidFillInfo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BidOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<string>("BidQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BidTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerSite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradingVolume")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DbPlacedOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
