// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace tradebot_sqlserver.Migrations
{
    [DbContext(typeof(TradeHistoryContext))]
    [Migration("20191004070620_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbPlacedOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AskFillInfo")
                        .HasColumnType("int");

                    b.Property<decimal?>("AskPrice")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<string>("AskQuote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AskTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BidFillInfo")
                        .HasColumnType("int");

                    b.Property<string>("BidOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<string>("BidQuote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("BrokerSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TradingVolume")
                        .HasColumnType("decimal(16, 8)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DbPlacedOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
